//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTITYEntities : DbContext
    {
        public DBCVENTITYEntities()
            : base("name=DBCVENTITYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDENEYIM> TBLDENEYIM { get; set; }
        public virtual DbSet<TBLILETIŞIM> TBLILETIŞIM { get; set; }
        public virtual DbSet<TBLSERTIFIKA> TBLSERTIFIKA { get; set; }
        public virtual DbSet<TBLYETENEK> TBLYETENEK { get; set; }
        public virtual DbSet<TBLDIL> TBLDIL { get; set; }
        public virtual DbSet<TBLEGITIM> TBLEGITIM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDA { get; set; }
    }
}
